server:
  port: 8080
  servlet:
    context-path: /study


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test
  driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.zpc.myself.study.test.dao
  mapper‐locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


